/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MultiFileDialog.java
 *
 * Created on Aug 16, 2010, 11:22:32 AM
 */

package NDL_JavaClassLib;

import java.awt.Frame;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.*;

/**
 *
 * @author Every one
 */
public class MultiFileDialog extends javax.swing.JDialog {
    private File[] Selection = null;
    private DefaultListModel FileListData = new DefaultListModel();
    
    private  int result;         //reporter varialble for various result underwhich the dialog is exitied.
    private final int OPEN = 1;
    private final int EXIT = 0;
    private final int SUCCESS = 2;
    private final int CLOSE = -1;
    private final int error = -2;
    
    /** Creates new form MultiFileDialog
     * @param parent
     * @param modal
     */
    public MultiFileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
         try {
              UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch(Exception e) {
              System.out.println("Error setting native LAF: " + e);
            }
        initComponents();
        //this.setVisible(true);
        FileList.setModel(FileListData);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FileList = new javax.swing.JList();
        FileSelDialog = new javax.swing.JFileChooser();
        AddButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        OpenButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Multiple Files in different directories");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);

        FileList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        FileList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                FileListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(FileList);

        FileSelDialog.setControlButtonsAreShown(false);
        FileSelDialog.setMultiSelectionEnabled(true);
        FileSelDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileSelDialogActionPerformed(evt);
            }
        });

        AddButton.setText("Add to List");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        RemoveButton.setText("Remove from List");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        OpenButton.setText("Open files");
        OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit ");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jSeparator1.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FileSelDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(RemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FileSelDialog, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(RemoveButton)
                    .addComponent(OpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_FileListValueChanged
        // TODO add your handling code here:
}//GEN-LAST:event_FileListValueChanged

    private void FileSelDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileSelDialogActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_FileSelDialogActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        this.addButtonAction();
    }
    public void addButtonAction(){
        Selection =  FileSelDialog.getSelectedFiles();
        if(Selection.length != 0)
            for ( int count = 0 ; count < Selection.length ; count++ ){
                String path = new String(Selection[count].getPath());
                if(! FileListData.contains(path))
                    FileListData.addElement(path);
            }
        if(FileListData.getSize() > 0)
            this.OpenButton.setEnabled(true);
        // TODO add your handling code here:
}//GEN-LAST:event_AddButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
       if (FileList.getSelectedIndices().length != 0){
            int SelInx[] = FileList.getSelectedIndices();
            String SelValues[] = new String [SelInx.length]; //FileList.getSelectedValues().;
            for(int count = 0; count < SelInx.length ; count ++)
                SelValues[count] = (String)FileListData.get(SelInx[count]);
            for(int count = 0 ; count < SelValues.length ; count++ )
                FileListData.removeElement(SelValues[count]);
            if(FileListData.getSize() == 0)
                this.OpenButton.setEnabled(false);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_RemoveButtonActionPerformed

    private void OpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenButtonActionPerformed
        //this.addButtonAction();
        if(FileListData.getSize() > 0){     //atleast one file has been selected
            this.result = this.SUCCESS;
        }else{
            this.result = this.OPEN;        //the dialog got closed through open buttone without selecting any files
                                            //ideal would be to display a message or diable the open button 
                                            // depending the length of selection list
        }
        this.setVisible(false);
                // TODO add your handling code here:
}//GEN-LAST:event_OpenButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        //this.setVisible(false);
        this.dispose();

        // TODO add your handling code here:
}//GEN-LAST:event_ExitButtonActionPerformed
    /**
     * Obtain a list of files that has been selected 
     * @return
     */
    public JList getList(){
    return FileList;
}

    /**
     *
     * @param str
     * @return
     */
    public String setOpenButtonTxt(String str){
    OpenButton.setText(str);
    return str;
}
    /**
     *
     * @param Instance
     * @param Cmd
     * @return
     */
    public String setOpenAction(ActionListener Instance, String Cmd){
        OpenButton.addActionListener(Instance);
        OpenButton.setActionCommand(Cmd);
        return OpenButton.getActionCommand();
}
    /**
     * 
     * @return
     */
    public String getOpenCommand() {
    return OpenButton.getActionCommand();
}
/**
 *
 * @return
 */
public String getCloseCommand() {
    return ExitButton.getActionCommand();
}
/**
 *
 * Returns the array of filenames that have been selected
 * @return
 */
 public String [] getSelectionArray(){
        int nFiles = FileListData.getSize();
        String [] Path = new String[nFiles];
        for(int i = 0 ; i < nFiles ; i++){
            Path[i] = (String) FileListData.get(i);
        }
        return Path;
    }
/**
 *
 * @param Instance
 * @param Cmd
 * @return
 */
public String  setCloseAction(ActionListener Instance, String Cmd){
    ExitButton.addActionListener (Instance);
    ExitButton.setActionCommand(Cmd);
    return ExitButton.getActionCommand();
}
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JList FileList;
    private javax.swing.JFileChooser FileSelDialog;
    private javax.swing.JButton OpenButton;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return
     */
    public String getDirectory() {
        //throw new UnsupportedOperationException("Not yet implemented");
        return FileSelDialog.getCurrentDirectory().getName();
    }

    /**
     * @return the result
     */
    public int getResult() {
        return result;
    }
}
